In [14]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
# define sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

print(sent)

['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy', 'I am a good developer', 'understand the meaning of words', 'your videos are good']


In [16]:
voc_size = 10000

In [17]:
one_hot_rep= [one_hot(words,voc_size)for words in sent]
one_hot_rep

[[476, 2412, 3453, 8934],
 [476, 2412, 3453, 9071],
 [476, 2038, 3453, 4468],
 [7829, 5520, 5578, 4340, 8466],
 [7829, 5520, 5578, 4340, 609],
 [1959, 476, 335, 3453, 8690],
 [4867, 6031, 7591, 4340]]

In [18]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [19]:
sent_max_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='post',maxlen=sent_max_length)
print(embedded_docs)

[[ 476 2412 3453 8934    0    0    0    0]
 [ 476 2412 3453 9071    0    0    0    0]
 [ 476 2038 3453 4468    0    0    0    0]
 [7829 5520 5578 4340 8466    0    0    0]
 [7829 5520 5578 4340  609    0    0    0]
 [1959  476  335 3453 8690    0    0    0]
 [4867 6031 7591 4340    0    0    0    0]]


In [20]:
dim = 10

In [21]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_max_length))
model.compile('adam','mse')

e:\Practice Projects\Basic\End to end project using simple RNN\rnnenv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step


array([[[-3.7014354e-02,  4.3562640e-02,  3.4724202e-02, -3.0333746e-02,
         -1.9051135e-05, -1.4717042e-02, -8.3655119e-03,  2.5892865e-02,
          2.9114831e-02, -1.3577759e-02],
        [-3.6969017e-02, -2.1934545e-02, -1.7624557e-02,  5.9259757e-03,
         -1.8906618e-02, -4.3615926e-02, -2.1017028e-02,  2.4141658e-02,
         -2.3538698e-02, -7.9298019e-04],
        [-3.1881608e-02, -2.8392483e-02,  2.6624147e-02,  4.8278991e-02,
          4.7088791e-02,  3.5133038e-02, -3.6643766e-02, -3.7318718e-02,
          4.1597728e-02, -7.6468699e-03],
        [-3.2576669e-02, -3.1256273e-02, -4.2831611e-02, -4.0012907e-02,
         -4.6244908e-02, -4.6870161e-02, -4.8598636e-02, -9.0590008e-03,
         -4.0262043e-02, -2.3162032e-02],
        [ 3.9963834e-03, -4.4076815e-03,  2.7848806e-02, -4.8190225e-02,
          3.1632733e-02, -2.2060288e-02, -4.9943317e-02,  2.0010296e-02,
          3.6781739e-02,  4.8443746e-02],
        [ 3.9963834e-03, -4.4076815e-03,  2.7848806e-02, -4.